# Generated by Ashen -- do NOT edit by hand, regenerated when the scheme changes
#
# The prompt was the last thing on this machine still wearing fixed 256-cube
# indices while everything else followed the wallpaper. Sourced from .zshrc
# AFTER ~/.p10k.zsh, so it overrides whatever that file decided -- which means
# it works with a p10k config this rice does not ship and never has to patch.
#
# Hex, not cube indices: p10k takes '#rrggbb' on a truecolor terminal, and the
# whole point is to land on the scheme's colour rather than the nearest of 256.

# Where you are: the accent, like every other "this is the thing" in the shell.
typeset -g POWERLEVEL9K_DIR_FOREGROUND='__ASHEN_ACCENT__'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='{{colors.outline.default.hex}}'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='__ASHEN_ACCENT__'

# The caret: accent when the last command was fine, error when it was not.
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='__ASHEN_ACCENT__'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='{{colors.error.default.hex}}'

# Git: clean is the quiet tone, anything that needs attention is the accent.
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='{{colors.on_surface_variant.default.hex}}'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='{{colors.tertiary.default.hex}}'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='__ASHEN_ACCENT2__'
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND='{{colors.outline.default.hex}}'

# Everything that is only context, never the point: dimmed to the outline.
typeset -g POWERLEVEL9K_TIME_FOREGROUND='{{colors.outline.default.hex}}'
typeset -g POWERLEVEL9K_RULER_FOREGROUND='{{colors.outline.default.hex}}'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='{{colors.outline.default.hex}}'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='__ASHEN_ACCENT__'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='{{colors.on_surface_variant.default.hex}}'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='{{colors.error.default.hex}}'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='{{colors.outline.default.hex}}'
typeset -g POWERLEVEL9K_BACKGROUND=
