// Ashen — idle timeouts (hypridle.conf generator).  by Adolf — github.com/AdolfLecompte
pragma Singleton
import Quickshell
import Quickshell.Io
import QtQuick

// hypridle has no runtime API, so Settings writes its own copy of the config
// under ~/.config/ashen and restarts the daemon against it. The shipped
// hypridle.conf stays the first-boot fallback and is never written to: it is
// a stow symlink, and editing it would dirty the user's checkout.
Singleton {
    id: root

    readonly property string confPath: Paths.config + "/hypridle.conf"

    // Seconds. 0 disables that listener entirely.
    readonly property int lockSecs: Prefs.idleLockSecs
    readonly property int screenOffSecs: Prefs.idleScreenOffSecs
    readonly property int suspendSecs: Prefs.idleSuspendSecs

    function listener(timeout, onTimeout, onResume) {
        if (timeout <= 0) return ""
        let block = "listener {\n    timeout = " + timeout + "\n    on-timeout = " + onTimeout + "\n"
        if (onResume !== "") block += "    on-resume = " + onResume + "\n"
        return block + "}\n\n"
    }

    function build() {
        return "# Generated by Ashen — edit from Settings > System > Idle & Suspend\n"
            + "general {\n"
            + "    lock_cmd = qs ipc -c ashen call lockscreen lock\n"
            // sleep 1 keeps hypridle's inhibitor held ~1s after firing the lock,
            // so the lock surface finishes grabbing input before the system
            // suspends. Without it the machine resumes frozen.
            + "    before_sleep_cmd = qs ipc -c ashen call lockscreen lock && sleep 1\n"
            + "    after_sleep_cmd = hyprctl dispatch dpms on\n"
            + "}\n\n"
            + root.listener(root.lockSecs, "qs ipc -c ashen call lockscreen lock", "")
            + root.listener(root.screenOffSecs, "hyprctl dispatch dpms off", "hyprctl dispatch dpms on")
            + root.listener(root.suspendSecs, "systemctl suspend", "")
    }

    // The config travels as an argv entry, never through the shell's parser,
    // so its newlines and quotes survive untouched.
    function write(alsoRestart) {
        let cmd = "mkdir -p \"$(dirname \"$2\")\" && printf %s \"$1\" > \"$2\""
        if (alsoRestart) cmd += " && { pkill -x hypridle; sleep 0.2; hypridle -c \"$2\" & disown; }"
        Quickshell.execDetached(["sh", "-c", cmd, "sh", root.build(), root.confPath])
    }

    // Keep Awake kills hypridle outright; this is how it comes back.
    function start() {
        Quickshell.execDetached(["sh", "-c",
            "pkill -x hypridle; sleep 0.2; hypridle -c '" + root.confPath + "' & disown"])
    }

    // Seed the file once prefs are in, then rewrite on every change. Writing
    // before `loaded` would put the defaults on disk over the saved values.
    property bool ready: false
    Connections {
        target: Prefs
        function onLoadedChanged() { if (Prefs.loaded && !root.ready) { root.ready = true; root.write(false) } }
    }
    Component.onCompleted: if (Prefs.loaded && !root.ready) { root.ready = true; root.write(false) }

    onLockSecsChanged: if (root.ready) root.write(true)
    onScreenOffSecsChanged: if (root.ready) root.write(true)
    onSuspendSecsChanged: if (root.ready) root.write(true)
}
