#!/usr/bin/env bash
# Builds modules/settings/SearchIndex.js: every Settings row label, keyed to
# the tab id that opens it. Run after adding or moving a Settings row.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
shell="$root/quickshell/.config/quickshell/ashen"
dir="$shell/modules/settings"
en="$shell/i18n/en.json"
out="${1:-$dir/SearchIndex.js}"

# Page file -> the most precise tab id that opens it.
map=(
    "SettingsLookTab.qml:look"
    "BarShapePage.qml:shape"     "BarLayoutPage.qml:layout"   "BarPage.qml:bar"
    "DesktopSurfacesPage.qml:dock" "DesktopPage.qml:desktop"
    "PanelsClockPage.qml:clock"  "PanelsMediaPage.qml:media"  "PanelsNotifyPage.qml:notify"
    "PanelsPage.qml:panels"
    "SettingsDisplayTab.qml:display"
    "SettingsSoundTab.qml:sound" "DevicesPage.qml:sound"
    "SettingsInputTab.qml:input" "InputPage.qml:input"
    "SettingsWifiTab.qml:wifi"   "SettingsBluetoothTab.qml:bluetooth" "NetworkPage.qml:network"
    "SettingsSystemTab.qml:system" "SystemPage.qml:system"
    "SettingsAboutTab.qml:about" "AboutPage.qml:about"
)

{
    echo ".pragma library"
    echo "// Generated by scripts/ashen-settings-index.sh -- do not edit by hand."
    echo "var entries = ["
    for pair in "${map[@]}"; do
        file="${pair%%:*}"; id="${pair##*:}"
        [ -f "$dir/$file" ] || continue
        { grep -oE 'I18n\.t\("settings\.[A-Za-z0-9_.]+"\)' "$dir/$file" || true; } \
            | sed -E 's/I18n\.t\("([^"]+)"\)/\1/' | sort -u \
            | while read -r key; do
                text=$(jq -r --arg k "$key" '.[$k] // ""' "$en")
                # Skip placeholders and one-word fragments like "On" or "All".
                case "$text" in *"{"*|"") continue ;; esac
                if [ "${#text}" -lt 4 ]; then continue; fi
                printf '    ["%s", "%s"],\n' "$id" "$key"
            done
    done
    echo "]"
} > "$out"
