-- Generated by Ashen (Settings > Input). Edited here, overwritten there.
local function app(which)
    return hl.dsp.exec_cmd("sh -c 'S=\"$HOME/ashen/scripts/ashen-app\"; "
        .. "[ -x \"$S\" ] || S=ashen-app; exec \"$S\" " .. which .. "'")
end
hl.bind("undefined", app("terminal"))
hl.bind("undefined", app("browser"))
hl.bind("undefined", app("files"))
hl.bind("undefined", app("editor"))
