import Quickshell
import Quickshell.Io
import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import "root:/services" as Services

Item {
    anchors.fill: parent

    Flickable {
        anchors.fill: parent
        anchors.margins: 28
        contentHeight: tab.implicitHeight
        clip: true
        boundsBehavior: Flickable.StopAtBounds

        ColumnLayout {
            id: tab
            width: parent.width
            spacing: 18

            // kitty appends "-<pid>" to the listen_on socket, so we have to walk
            // whichever ones exist instead of assuming the exact path.
            readonly property string kittySockets: "/tmp/kitty-ashen.sock-*"

    property string currentFont: "JetBrainsMono NF"

    property var schemes: {
        "classic": { abyss: "#080809", void_: "#0f0f11", crypt: "#16161a", surface: "#1c1c21", raised: "#242428", elevated: "#2e2e34", snow: "#e8e8ec", mist: "#9090a0", ash: "#4a4a54", ghost: "#6e6e7a", shade: "#4e4e5a", error_: "#c87a7a", neutral: "#8a8a96", papirusColor: "grey" },
        "cyberpunk": { abyss: "#0d0221", void_: "#150829", crypt: "#1a0b2e", surface: "#241b3d", raised: "#2d2347", elevated: "#3a2d5c", snow: "#f0f0ff", mist: "#b8a9d9", ash: "#5e4b8b", ghost: "#ff2e97", shade: "#cc1f7a", error_: "#ff3860", neutral: "#00fff2", papirusColor: "magenta" },
        "tokyonight": { abyss: "#16161e", void_: "#1a1b26", crypt: "#1f2335", surface: "#24283b", raised: "#292e42", elevated: "#364a82", snow: "#c0caf5", mist: "#a9b1d6", ash: "#565f89", ghost: "#7aa2f7", shade: "#3d59a1", error_: "#f7768e", neutral: "#bb9af7", papirusColor: "blue" },
        "dracula": { abyss: "#21222c", void_: "#282a36", crypt: "#2d2f3f", surface: "#343746", raised: "#44475a", elevated: "#4d5066", snow: "#f8f8f2", mist: "#9ba0c4", ash: "#6272a4", ghost: "#bd93f9", shade: "#9580c9", error_: "#ff5555", neutral: "#ff79c6", papirusColor: "violet" },
        "nord": { abyss: "#2e3440", void_: "#3b4252", crypt: "#434c5e", surface: "#434c5e", raised: "#4c566a", elevated: "#4c566a", snow: "#eceff4", mist: "#d8dee9", ash: "#4c566a", ghost: "#88c0d0", shade: "#5e81ac", error_: "#bf616a", neutral: "#b48ead", papirusColor: "cyan" },
    }

    Component.onCompleted: fontCheckProc.running = true
    Process {
        id: fontCheckProc
        command: ["sh", "-c", "grep -o '<string>[^<]*</string>' /home/adolf/.config/fontconfig/fonts.conf 2>/dev/null | tail -1 | sed 's/<[^>]*>//g'"]
        running: false
        stdout: StdioCollector {
            onStreamFinished: {
                let f = text.trim()
                if (f.length > 0) tab.currentFont = f
            }
        }
    }

    function applyFont(fontName) {
        tab.currentFont = fontName
        let xml = fontName === 'JetBrainsMono NF'
            ? '<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig></fontconfig>'
            : '<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><match target="pattern"><test name="family"><string>JetBrainsMono NF</string></test><edit name="family" mode="assign" binding="strong"><string>' + fontName + '</string></edit></match></fontconfig>'
        let b64 = Qt.btoa(xml)
        Quickshell.execDetached(["sh", "-c",
            "mkdir -p ~/.config/fontconfig && echo '" + b64 + "' | base64 -d > ~/.config/fontconfig/fonts.conf && fc-cache -f && pkill -9 quickshell; sleep 0.3; quickshell -c ashen &"
        ])
    }

    function applyScheme(schemeId) {
        let c = tab.schemes[schemeId]
        if (!c) return
        let json = JSON.stringify({
            abyss: c.abyss, void_: c.void_, crypt: c.crypt, surface: c.surface,
            raised: c.raised, elevated: c.elevated, snow: c.snow, mist: c.mist,
            ash: c.ash, ghost: c.ghost, shade: c.shade, error_: c.error_, neutral: c.neutral
        })
        let b64 = Qt.btoa(json)
        let borderHex = c.ghost.replace("#", "") + "ff"
        Quickshell.execDetached(["sh", "-c",
            "echo '" + b64 + "' | base64 -d > /home/adolf/.cache/ashen_scheme.json && " +
            "echo '" + schemeId + "' > /home/adolf/.cache/ashen_scheme_mode.txt && " +
            "hyprctl eval \"hl.config({ general = { col = { active_border = { colors = {'rgba(" + borderHex + ")'} } } } })\" && " +
            "sed -i 's/active_border = { colors = {\"rgba([^)]*)\"} }/active_border = { colors = {\"rgba(" + borderHex + ")\"} }/' /home/adolf/ashen/hypr/.config/hypr/conf/general.lua"
        ])
        tab.applyGtkTheme(c)
        tab.applyKittyTheme(c)
        tab.applyP10kTheme(c)
    }

    function applyKittyTheme(c) {
        let conf = '# Generated by Ashen -- do NOT edit by hand, regenerated when the scheme changes\n' +
            'foreground            ' + c.snow + '\n' +
            'background            ' + c.abyss + '\n' +
            'selection_foreground  ' + c.abyss + '\n' +
            'selection_background  ' + c.ghost + '\n' +
            'cursor                ' + c.ghost + '\n' +
            'color0  ' + c.abyss + '\n' +
            'color1  ' + c.error_ + '\n' +
            'color2  #5a7a6a\n' +
            'color3  #8a7a5a\n' +
            // ANSI blue is the scheme accent (same as in p10k), so whatever the
            // terminal paints as "blue" follows the theme: fastfetch,
            // prompt, etc.
            'color4  ' + c.ghost + '\n' +
            'color5  #a89bc8\n' +
            'color6  #5a7a8a\n' +
            'color7  ' + c.mist + '\n' +
            'color8  ' + c.ash + '\n' +
            'color9  ' + c.error_ + '\n' +
            'color10 #7a9e7e\n' +
            'color11 #c4a882\n' +
            'color12 ' + c.neutral + '\n' +
            'color13 #c8b8e8\n' +
            'color14 #7aaabb\n' +
            'color15 ' + c.snow + '\n'
        let b64 = Qt.btoa(conf)
        Quickshell.execDetached(["sh", "-c",
            "echo '" + b64 + "' | base64 -d > \"$HOME/.config/kitty/ashen-colors.conf\" && " +
            "for s in " + tab.kittySockets + "; do kitten @ --to \"unix:$s\" set-colors --all " +
            "foreground=" + c.snow + " background=" + c.abyss + " " +
            "selection_foreground=" + c.abyss + " selection_background=" + c.ghost + " " +
            "cursor=" + c.ghost + " color0=" + c.abyss + " color1=" + c.error_ + " " +
            "color7=" + c.mist + " color8=" + c.ash + " color9=" + c.error_ + " color15=" + c.snow + " " +
            "2>/dev/null; done"
        ])
    }

    function applyP10kTheme(c) {
        Quickshell.execDetached(["sh", "-c",
            "sed -i \"s/^  local grey=.*/  local grey='" + c.mist + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local red=.*/  local red='" + c.error_ + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local yellow=.*/  local yellow='" + c.neutral + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local blue=.*/  local blue='" + c.ghost + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local magenta=.*/  local magenta='" + c.ghost + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local cyan=.*/  local cyan='" + c.shade + "'/\" /home/adolf/.p10k.zsh && " +
            "sed -i \"s/^  local white=.*/  local white='" + c.snow + "'/\" /home/adolf/.p10k.zsh && " +
            "for s in " + tab.kittySockets + "; do kitten @ --to \"unix:$s\" send-text --match all $'source ~/.p10k.zsh\r' 2>/dev/null; done"
        ])
    }

    function applyGtkTheme(c) {
        let css = '/* ══════════════════════════════════════\n' +
            '   Ashen Ghost -- GTK3 overrides for Nemo\n' +
            '   ══════════════════════════════════════ */\n' +
            'toolbar, GtkToolbar {\n' +
            '    background-color: transparent;\n' +
            '    background-image: none;\n' +
            '    box-shadow: none;\n' +
            '    border: none;\n' +
            '}\n' +
            '.sidebar row:selected,\n' +
            '.sidebar row:selected:focus {\n' +
            '    background-color: ' + c.ghost + ';\n' +
            '    color: ' + c.abyss + ';\n' +
            '}\n' +
            'iconview.view:selected,\n' +
            'iconview.view:selected:focus,\n' +
            '.view:selected,\n' +
            '.view:selected:focus {\n' +
            '    background-color: alpha(' + c.ghost + ', 0.35);\n' +
            '    color: ' + c.snow + ';\n' +
            '    border-radius: 6px;\n' +
            '}\n' +
            'window, .background {\n' +
            '    background-color: alpha(' + c.void_ + ', 0.001);\n' +
            '    color: ' + c.snow + ';\n' +
            '}\n' +
            '.sidebar {\n' +
            '    background-color: ' + c.surface + ';\n' +
            '}\n' +
            '.view,\n' +
            'iconview.view,\n' +
            'iconview {\n' +
            '    background-color: alpha(' + c.void_ + ', 0.001);\n' +
            '}\n' +
            '.sidebar,\n' +
            '.sidebar .view,\n' +
            'placessidebar {\n' +
            '    background-color: alpha(' + c.surface + ', 0.15);\n' +
            '}\n' +
            'button {\n' +
            '    border-radius: 8px;\n' +
            '}\n' +
            'dialog,\n' +
            'window.dialog,\n' +
            '.background.csd {\n' +
            '    border-radius: 12px;\n' +
            '}\n' +
            'button.suggested-action {\n' +
            '    background-color: ' + c.ghost + ';\n' +
            '    background-image: none;\n' +
            '    color: ' + c.abyss + ';\n' +
            '    border-color: ' + c.ghost + ';\n' +
            '}\n' +
            'button.suggested-action:hover {\n' +
            '    background-color: ' + c.neutral + ';\n' +
            '}\n' +
            'button.suggested-action:active {\n' +
            '    background-color: ' + c.shade + ';\n' +
            '}\n' +
            'list row:selected,\n' +
            'list row:selected:focus,\n' +
            'treeview:selected,\n' +
            'treeview:selected:focus {\n' +
            '    background-color: ' + c.ghost + ';\n' +
            '    color: ' + c.abyss + ';\n' +
            '}\n' +
            'check:checked,\n' +
            'radio:checked,\n' +
            'switch:checked {\n' +
            '    background-color: ' + c.ghost + ';\n' +
            '    border-color: ' + c.ghost + ';\n' +
            '}\n' +
            'selection,\n' +
            'entry selection,\n' +
            'textview text selection,\n' +
            'label selection {\n' +
            '    background-color: ' + c.ghost + ';\n' +
            '    color: ' + c.abyss + ';\n' +
            '}\n' +
            '.floating-bar {\n' +
            '    background-color: alpha(' + c.surface + ', 0.92);\n' +
            '    color: ' + c.snow + ';\n' +
            '    border: 1px solid alpha(' + c.ghost + ', 0.3);\n' +
            '    border-radius: 10px;\n' +
            '    padding: 4px 10px;\n' +
            '    box-shadow: none;\n' +
            '}\n' +
            '.floating-bar:backdrop {\n' +
            '    background-color: alpha(' + c.surface + ', 0.75);\n' +
            '}\n'
        let b64 = Qt.btoa(css)
        let papirusCmd = c.papirusColor ? ("papirus-folders -C " + c.papirusColor + " 2>/dev/null; ") : ""
        Quickshell.execDetached(["sh", "-c",
            "mkdir -p /home/adolf/.config/gtk-3.0 && " +
            "echo '" + b64 + "' | base64 -d > /home/adolf/.config/gtk-3.0/gtk.css && " +
            papirusCmd
        ])
    }

    Text {
        text: "Theme"
        color: Services.Colors.snow
        font.pixelSize: 20
        font.bold: true
        font.family: "JetBrainsMono NF"
    }
    ColumnLayout {
        id: schemeSection
        Layout.fillWidth: true
        spacing: 8

        property string activeScheme: "classic"
        // merged into single onCompleted below
        Process {
            id: schemeModeReadProc
            command: ["sh", "-c", "cat /home/adolf/.cache/ashen_scheme_mode.txt 2>/dev/null"]
            running: false
            stdout: StdioCollector {
                onStreamFinished: {
                    let s = text.trim()
                    if (s.length > 0) schemeSection.activeScheme = s
                }
            }
        }
        RowLayout {
            spacing: 10
            Text { text: ""; font.family: "Material Symbols Rounded"; font.pixelSize: 18; color: Services.Colors.ghost }
            Text { text: "Color Scheme"; color: Services.Colors.snow; font.pixelSize: 13; font.bold: true; font.family: "JetBrainsMono NF" }
        }

        Flow {
            Layout.fillWidth: true
            spacing: 10
            Repeater {
                model: [
                    { id: "classic", label: "Classic", subtitle: "Ashen Ghost", swatches: ["#080809", "#1c1c21", "#6e6e7a", "#e8e8ec"] },
                    { id: "cyberpunk", label: "Cyberpunk", subtitle: "Neon nights", swatches: ["#0d0221", "#241b3d", "#ff2e97", "#00fff2"] },
                    { id: "tokyonight", label: "Tokyo Night", subtitle: "Calm blues", swatches: ["#1a1b26", "#24283b", "#7aa2f7", "#bb9af7"] },
                    { id: "dracula", label: "Dracula", subtitle: "Classic dark", swatches: ["#282a36", "#343746", "#bd93f9", "#ff79c6"] },
                    { id: "nord", label: "Nord", subtitle: "Arctic cool", swatches: ["#2e3440", "#434c5e", "#88c0d0", "#b48ead"] },
                    { id: "dynamic", label: "Dynamic", subtitle: "From wallpaper", swatches: [] },
                ]
                delegate: Rectangle {
                    required property var modelData
                    width: 150; height: 80
                    radius: 12
                    color: Services.Colors.ghostAlpha(0.15)
                    Behavior on color { ColorAnimation { duration: 150 } }
                    ColumnLayout {
                        anchors.centerIn: parent
                        spacing: 6
                        ColumnLayout {
                            spacing: 2
                            Text { text: modelData.label; color: Services.Colors.snow; font.pixelSize: 13; font.bold: true; font.family: "JetBrainsMono NF"; Layout.alignment: Qt.AlignHCenter }
                            Text { text: modelData.subtitle; color: Services.Colors.mist; font.pixelSize: 10; font.family: "JetBrainsMono NF"; Layout.alignment: Qt.AlignHCenter }
                        }
                        Row {
                            Layout.alignment: Qt.AlignHCenter
                            spacing: 4
                            visible: modelData.swatches.length > 0
                            Repeater {
                                model: modelData.swatches
                                delegate: Rectangle {
                                    required property string modelData
                                    width: 16; height: 16
                                    radius: 5
                                    color: modelData
                                    border.color: Qt.rgba(1, 1, 1, 0.15)
                                    border.width: 1
                                }
                            }
                        }
                    }
                    Rectangle {
                        visible: schemeSection.activeScheme === modelData.id
                        anchors.top: parent.top
                        anchors.right: parent.right
                        anchors.margins: 6
                        width: 18; height: 18
                        radius: 9
                        color: Services.Colors.ghost
                        Text {
                            anchors.centerIn: parent
                            text: "\uf0be"
                            font.family: "Material Symbols Rounded"
                            font.pixelSize: 11
                            color: Services.Colors.abyss
                        }
                    }
                    MouseArea {
                        anchors.fill: parent
                        cursorShape: Qt.PointingHandCursor
                        hoverEnabled: true
                        onEntered: parent.color = Services.Colors.ghostAlpha(0.3)
                        onExited: parent.color = Services.Colors.ghostAlpha(0.15)
                        onClicked: {
                            if (modelData.id === "dynamic") {
                                schemeSection.activeScheme = "dynamic"
                                Quickshell.execDetached(["sh", "-c",
                                    "echo 'dynamic' > /home/adolf/.cache/ashen_scheme_mode.txt && " +
                                    "matugen image \"$(awww query | grep -o 'image: .*' | cut -d' ' -f2)\" --mode dark --source-color-index 0 --type $(cat /home/adolf/.cache/ashen_dynamic_type.txt 2>/dev/null || echo scheme-tonal-spot)"
                                ])
                            } else {
                                schemeSection.activeScheme = modelData.id
                                tab.applyScheme(modelData.id)
                            }
                        }
                    }
                }
            }
        }
        Text { text: "'Dynamic' opens the wallpaper picker -- colors regenerate automatically when you pick one"; color: Services.Colors.ash; font.pixelSize: 10; font.family: "JetBrainsMono NF"; wrapMode: Text.WordWrap; Layout.fillWidth: true }

        Text { text: "Dynamic Style"; color: Services.Colors.snow; font.pixelSize: 12; font.bold: true; font.family: "JetBrainsMono NF"; Layout.topMargin: 10 }
        Text { text: "How aggressively Dynamic pulls color from the wallpaper"; color: Services.Colors.ash; font.pixelSize: 10; font.family: "JetBrainsMono NF" }

        property string dynamicType: "scheme-tonal-spot"
        Component.onCompleted: {
            schemeModeReadProc.running = true
            dynTypeProc.running = true
        }
        Process {
            id: dynTypeProc
            command: ["sh", "-c", "cat /home/adolf/.cache/ashen_dynamic_type.txt 2>/dev/null"]
            running: false
            stdout: StdioCollector {
                onStreamFinished: {
                    let t = text.trim()
                    if (t.length > 0) schemeSection.dynamicType = t
                }
            }
        }
        function setDynamicType(t) {
            schemeSection.dynamicType = t
            Quickshell.execDetached(["sh", "-c", "echo '" + t + "' > /home/adolf/.cache/ashen_dynamic_type.txt"])
        }

        Flow {
            Layout.fillWidth: true
            spacing: 8
            Repeater {
                model: [
                    { id: "scheme-monochrome", label: "Monochrome" },
                    { id: "scheme-neutral", label: "Neutral" },
                    { id: "scheme-tonal-spot", label: "Tonal Spot" },
                    { id: "scheme-vibrant", label: "Vibrant" },
                    { id: "scheme-expressive", label: "Expressive" },
                    { id: "scheme-fidelity", label: "Fidelity" },
                    { id: "scheme-content", label: "Content" },
                    { id: "scheme-rainbow", label: "Rainbow" },
                    { id: "scheme-fruit-salad", label: "Fruit Salad" },
                ]
                delegate: Rectangle {
                    required property var modelData
                    width: dynRow.implicitWidth + 20
                    height: 32
                    radius: 8
                    color: schemeSection.dynamicType === modelData.id ? Services.Colors.ghost : Services.Colors.ghostAlpha(0.12)
                    Behavior on color { ColorAnimation { duration: 150 } }
                    RowLayout {
                        id: dynRow
                        anchors.centerIn: parent
                        spacing: 5
                        Text {
                            visible: schemeSection.dynamicType === modelData.id
                            text: ""
                            font.family: "Material Symbols Rounded"
                            font.pixelSize: 11
                            color: Services.Colors.abyss
                        }
                        Text {
                            text: modelData.label
                            font.pixelSize: 11
                            font.family: "JetBrainsMono NF"
                            color: schemeSection.dynamicType === modelData.id ? Services.Colors.abyss : Services.Colors.snow
                        }
                    }
                    MouseArea {
                        anchors.fill: parent
                        cursorShape: Qt.PointingHandCursor
                        onClicked: schemeSection.setDynamicType(modelData.id)
                    }
                }
            }
        }
    }

    Rectangle { Layout.fillWidth: true; height: 1; color: Services.Colors.ghostAlpha(0.15) }

    RowLayout {
        Layout.fillWidth: true
        spacing: 12
        Text { text: ""; font.family: "Material Symbols Rounded"; font.pixelSize: 20; color: Services.Colors.ghost }
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 2
            Text { text: "Wallpaper"; color: Services.Colors.snow; font.pixelSize: 13; font.bold: true; font.family: "JetBrainsMono NF" }
            Text { text: "Choose or add wallpapers"; color: Services.Colors.mist; font.pixelSize: 10; font.family: "JetBrainsMono NF" }
        }
        Rectangle {
            width: 90; height: 34
            radius: 8
            color: Services.Colors.ghostAlpha(0.15)
            Behavior on color { ColorAnimation { duration: 150 } }
            Text { anchors.centerIn: parent; text: "Open"; color: Services.Colors.snow; font.pixelSize: 12; font.family: "JetBrainsMono NF" }
            MouseArea {
                anchors.fill: parent
                cursorShape: Qt.PointingHandCursor
                hoverEnabled: true
                onEntered: parent.color = Services.Colors.ghostAlpha(0.3)
                onExited: parent.color = Services.Colors.ghostAlpha(0.15)
                onClicked: {
                    Services.AppState.settingsVisible = false
                    Services.AppState.wallpaperVisible = true
                }
            }
        }
    }

    Rectangle { Layout.fillWidth: true; height: 1; color: Services.Colors.ghostAlpha(0.15) }

    ColumnLayout {
        Layout.fillWidth: true
        spacing: 8
        RowLayout {
            spacing: 10
            Text { text: ""; font.family: "Material Symbols Rounded"; font.pixelSize: 18; color: Services.Colors.ghost }
            Text { text: "System Font"; color: Services.Colors.snow; font.pixelSize: 13; font.bold: true; font.family: "JetBrainsMono NF" }
        }
        Text { text: "Restarts the shell to apply"; color: Services.Colors.ash; font.pixelSize: 10; font.family: "JetBrainsMono NF" }

        Flow {
            Layout.fillWidth: true
            spacing: 8
            Repeater {
                model: [
                    "JetBrainsMono NF",
                    "FiraCode Nerd Font",
                    "Hack Nerd Font",
                    "CaskaydiaCove Nerd Font",
                    "Iosevka Nerd Font",
                    "MesloLGS Nerd Font",
                    "ProggyClean Nerd Font",
                ]
                delegate: Rectangle {
                    required property string modelData
                    width: fontLabelRow.implicitWidth + 24
                    height: 36
                    radius: 8
                    color: tab.currentFont === modelData ? Services.Colors.ghost : Services.Colors.ghostAlpha(0.12)
                    Behavior on color { ColorAnimation { duration: 150 } }
                    RowLayout {
                        id: fontLabelRow
                        anchors.centerIn: parent
                        spacing: 6
                        Text {
                            visible: tab.currentFont === modelData
                            text: "\uf0be"
                            font.family: "Material Symbols Rounded"
                            font.pixelSize: 12
                            color: Services.Colors.abyss
                        }
                        Text {
                            text: modelData
                            font.pixelSize: 12
                            font.family: modelData
                            color: tab.currentFont === modelData ? Services.Colors.abyss : Services.Colors.snow
                        }
                    }
                    MouseArea {
                        anchors.fill: parent
                        cursorShape: Qt.PointingHandCursor
                        onClicked: tab.applyFont(modelData)
                    }
                }
            }
        }
    }

    Item { Layout.preferredHeight: 8 }
        }
    }
}
